apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: auth-dual-role
  namespace: kantrip-sandbox
  labels:
    strimzi.io/cluster: auth-kantrip
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: persistent-claim
    size: 1Gi
    deleteClaim: true
---
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: auth-kantrip
  namespace: kantrip-sandbox
spec:
  kafka:
    version: ${KAFKA_VERSION}
    metadataVersion: 4.3-IV0
    listeners:
      - name: provision
        port: 9092
        type: internal
        tls: false
      - name: plain
        port: 9097
        type: nodeport
        tls: true
        authentication:
          type: custom
          sasl: true
          listenerConfig:
            sasl.enabled.mechanisms: PLAIN
            plain.sasl.jaas.config: '${file:/mnt/auth-users/plain-jaas.properties:plain-jaas-config}'
        configuration:
          brokerCertChainAndKey:
            secretName: kafka-listeners-tls
            certificate: tls.crt
            key: tls.key
          bootstrap:
            nodePort: 30097
          brokers:
            - broker: 0
              advertisedHost: localhost
              advertisedPort: 9097
      - name: scram256
        port: 9098
        type: nodeport
        tls: true
        authentication:
          type: custom
          sasl: true
          listenerConfig:
            sasl.enabled.mechanisms: SCRAM-SHA-256
            scram-sha-256.sasl.jaas.config: >-
              org.apache.kafka.common.security.scram.ScramLoginModule required;
        configuration:
          brokerCertChainAndKey:
            secretName: kafka-listeners-tls
            certificate: tls.crt
            key: tls.key
          bootstrap:
            nodePort: 30098
          brokers:
            - broker: 0
              advertisedHost: localhost
              advertisedPort: 9098
    config:
      auto.create.topics.enable: false
      default.replication.factor: 1
      min.insync.replicas: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
      config.providers: file
      config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    authorization:
      type: simple
      superUsers:
        - ANONYMOUS
        - kantrip-plain
        - kantrip-scram-256
    template:
      pod:
        volumes:
          - name: auth-users
            secret:
              secretName: auth-kafka-users
              items:
                - key: plain-jaas.properties
                  path: plain-jaas.properties
      kafkaContainer:
        volumeMounts:
          - name: auth-users
            mountPath: /mnt/auth-users
            readOnly: true
