[mypy]
strict = True
disallow_subclassing_any = False
disallow_any_generics = False

[mypy-cloup.*]
ignore_missing_imports = True

[mypy-jsonschema.*]
ignore_missing_imports = True

[mypy-keyring.*]
ignore_missing_imports = True

[mypy-yaml.*]
ignore_missing_imports = True
