"""Prepare consistent interactive Bash, Zsh, and Fish profile sessions."""

from __future__ import annotations

import os
import shlex
import shutil
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import TextIO

from kantrip.adapters import ADAPTER_EXECUTABLES

SUPPORTED_SHELLS = frozenset({"bash", "fish", "zsh"})


class ShellError(ValueError):
    """Raised when an interactive shell cannot be prepared."""


@dataclass(frozen=True)
class ShellPlan:
    """Arguments and environment changes for an interactive child shell."""

    arguments: tuple[str, ...]
    environment_overrides: dict[str, str]


def resolve_interactive_shell(environment: Mapping[str, str]) -> str:
    """Resolve and validate the shell selected for an interactive session."""
    configured = environment.get("SHELL")
    if configured:
        executable = configured
        resolved = shutil.which(executable, path=environment.get("PATH"))
    else:
        resolved = shutil.which("bash", path=environment.get("PATH"))
        executable = resolved or ""
        if resolved is None:
            raise ShellError(
                "SHELL is not set and Bash could not be found; install Bash or set SHELL "
                "to Bash, Zsh, or Fish"
            )

    shell_name = Path(executable).name
    if shell_name not in SUPPORTED_SHELLS:
        supported = ", ".join(name.capitalize() for name in ("bash", "zsh", "fish"))
        raise ShellError(f"interactive shell '{shell_name}' is not supported; use {supported}")
    if resolved is None:
        raise ShellError(f"interactive shell '{executable}' was not found")
    return resolved


def prepare_interactive_shell(
    shell: str,
    session_directory: Path,
    shim_directory: Path,
    environment: Mapping[str, str],
) -> ShellPlan:
    """Create shell-specific startup state while preserving normal user configuration."""
    shell_name = Path(shell).name
    if shell_name == "bash":
        return _prepare_bash(shell, session_directory, shim_directory, environment)
    if shell_name == "zsh":
        return _prepare_zsh(shell, session_directory, shim_directory, environment)
    if shell_name == "fish":
        return _prepare_fish(shell, shim_directory)
    raise ShellError(f"interactive shell '{shell_name}' is not supported")


def quote_shell_argument(shell_name: str, value: str) -> str:
    """Quote one literal argument for a supported shell's command language."""
    if shell_name == "fish":
        return _fish_quote(value)
    if shell_name in {"bash", "zsh"}:
        return shlex.quote(value)
    raise ShellError(f"interactive shell '{shell_name}' is not supported")


def _prepare_bash(
    shell: str,
    session_directory: Path,
    shim_directory: Path,
    environment: Mapping[str, str],
) -> ShellPlan:
    home = environment.get("HOME")
    original_startup = Path(home).expanduser() / ".bashrc" if home else None
    startup_path = session_directory / "bashrc"
    _write_private_file(
        startup_path,
        _render_posix_startup(original_startup, shim_directory, refresh_command="hash -r"),
    )
    return ShellPlan((shell, "--rcfile", str(startup_path)), {})


def _prepare_zsh(
    shell: str,
    session_directory: Path,
    shim_directory: Path,
    environment: Mapping[str, str],
) -> ShellPlan:
    startup_directory = session_directory / "zsh"
    startup_directory.mkdir(mode=0o700)
    original_directory = environment.get("ZDOTDIR") or environment.get("HOME")
    original_startup = (
        Path(original_directory).expanduser() / ".zshrc" if original_directory else None
    )
    history_path = (
        Path(original_directory).expanduser() / ".zsh_history" if original_directory else None
    )
    contents = _render_zsh_startup(
        original_startup,
        shim_directory,
        history_path=history_path,
        original_zdotdir=environment.get("ZDOTDIR"),
        original_shell_sessions_disable=environment.get("SHELL_SESSIONS_DISABLE"),
    )
    _write_private_file(startup_directory / ".zshrc", contents)
    return ShellPlan(
        (shell,),
        {"ZDOTDIR": str(startup_directory), "SHELL_SESSIONS_DISABLE": "1"},
    )


def _prepare_fish(shell: str, shim_directory: Path) -> ShellPlan:
    lines = [*_fish_shadow_cleanup(), f"set -gx PATH {_fish_quote(str(shim_directory))} $PATH"]
    return ShellPlan((shell, "--init-command", "; ".join(lines)), {})


def _render_posix_startup(
    original_startup: Path | None,
    shim_directory: Path,
    *,
    refresh_command: str,
) -> str:
    lines = ["# Generated by Kantrip for this profile session."]
    if original_startup is not None and original_startup.is_file():
        lines.append(f"source {shlex.quote(str(original_startup))}")
    lines.extend(_posix_shadow_cleanup())
    lines.extend(
        (
            f'export PATH={shlex.quote(str(shim_directory))}:"${{PATH:-{os.defpath}}}"',
            refresh_command,
        )
    )
    return "\n".join(lines) + "\n"


def _render_zsh_startup(
    original_startup: Path | None,
    shim_directory: Path,
    *,
    history_path: Path | None,
    original_zdotdir: str | None,
    original_shell_sessions_disable: str | None,
) -> str:
    lines = ["# Generated by Kantrip for this profile session."]
    if original_zdotdir is not None:
        lines.append(f"export ZDOTDIR={shlex.quote(original_zdotdir)}")
    else:
        lines.append("unset ZDOTDIR")
    if original_shell_sessions_disable is not None:
        lines.append(
            "export SHELL_SESSIONS_DISABLE=" f"{shlex.quote(original_shell_sessions_disable)}"
        )
    else:
        lines.append("unset SHELL_SESSIONS_DISABLE")
    if history_path is not None:
        lines.append(f"HISTFILE={shlex.quote(str(history_path))}")
    if original_startup is not None and original_startup.is_file():
        lines.append(f"source {shlex.quote(str(original_startup))}")
    lines.extend(_posix_shadow_cleanup())
    lines.extend(
        (
            f'export PATH={shlex.quote(str(shim_directory))}:"${{PATH:-{os.defpath}}}"',
            "rehash",
        )
    )
    return "\n".join(lines) + "\n"


def _posix_shadow_cleanup() -> list[str]:
    lines: list[str] = []
    for executable in sorted(ADAPTER_EXECUTABLES):
        quoted = shlex.quote(executable)
        lines.append(f"unalias {quoted} 2>/dev/null || :")
        lines.append(f"unset -f {quoted} 2>/dev/null || :")
    return lines


def _fish_shadow_cleanup() -> list[str]:
    lines: list[str] = []
    for executable in sorted(ADAPTER_EXECUTABLES):
        quoted = _fish_quote(executable)
        lines.append(f"functions --erase {quoted} 2>/dev/null")
        lines.append(f"abbr --erase {quoted} 2>/dev/null")
    return lines


def _fish_quote(value: str) -> str:
    """Quote one literal Fish argument without relying on POSIX shell syntax."""
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def _write_private_file(path: Path, contents: str) -> None:
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    stream: TextIO
    with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
        stream.write(contents)


__all__ = [
    "SUPPORTED_SHELLS",
    "ShellError",
    "ShellPlan",
    "prepare_interactive_shell",
    "quote_shell_argument",
    "resolve_interactive_shell",
]
