profiles:
  local:
    id: 018f8f13-7c21-7cee-8000-000000000001
    description: Local development
    labels:
      environment: local
    kafka:
      bootstrapServers:
        - localhost:9092
      transport: plaintext
      auth:
        type: none
